# Specifies to the build target as a free-standing x86_64 program. More info at:
# <https://doc.rust-lang.org/rustc/platform-support/x86_64-unknown-none.html>.
[build]
#build-stage = 1
target = ["x86_64-unknown-none"]

# Unwinding is meaningless here.
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

# See more keys and their definitions at:
# <https://doc.rust-lang.org/cargo/reference/config.html>.