name:                pirate-radio
version:             0.1.0
github:              "ona-li-toki-e-jan-Epiphany-tawa-mi/pirate-radio"
license:             MIT
author:              "ona li toki e jan Epiphany tawa mi"
maintainer:          "darklorddudeal.deaddear@gmail.com"
copyright:           "2022 Nathaniel Needham"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ona-li-toki-e-jan-Epiphany-tawa-mi/pirate-radio#readme>

dependencies:
- base
- http-conduit 
- http-types
- bytestring
- utf8-string 
- dns
- aeson
- uuid-types
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  pirate-radio-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
