/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guitarthang_epiphany_lamestuff_nativecode_windows_WinUSB */

#ifndef _Included_com_guitarthang_epiphany_lamestuff_nativecode_windows_WinUSB
#define _Included_com_guitarthang_epiphany_lamestuff_nativecode_windows_WinUSB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guitarthang_epiphany_lamestuff_nativecode_windows_WinUSB
 * Method:    printfff
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_guitarthang_epiphany_lamestuff_nativecode_windows_WinUSB_printfff
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
