/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Printer */

#ifndef _Included_Printer
#define _Included_Printer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Printer
 * Method:    printfff
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Printer_printfff
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
